sudo: required
dist: trusty
language: android
group: edge
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
android:
  components:
  - tools
  - android-27
  - platform-tools
  - build-tools-27.0.3
  - extra-android-m2repository
  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - '.+'
branches:
  only:
  - master
env:
  matrix:
  - COMPONENT=unit
  - COMPONENT=sample_todo
  - COMPONENT=sample_weather
  - COMPONENT=sample_counter
  - COMPONENT=build
  global:
    # zenSonatypeUsername
    - secure: "NC/3me/7wbH6/OOXFu+LDGPEb4Xl33UVZ2D0Syi4q417lfEjFi7l8gqFi99WDZtXr6b4Q/ypE5mNOj6Fndn2s5uoTGdZ8/aNU25D+qRroKA0+zFP5bgDCyvsAtISwVIqxRLhv8GVLIthzSj/3RaxQN62zvt9Lxe2pr9T6vsVT4r9KnVj6yIPfKhw8g1FVHgVsMzMUmUOBf3s07gBbeQWb3g1zhN0ELPTZJOhm1meMlAvTZNxS/GaBKiJ42YCkelJKfv/+qJdJDJpHkzNkf3694WtrlSCUc1IF0DpvnGBuFhIK8JtMS5qkk9aDHIZ2oOo4+wYmSuYZqHMRbZmzBzhqrsbuc5aIemSMHpAY1cHNWC6HnFY2i3OKC3XToVZP1X1xmSI4lgZOaOjXalBBnFbFOMg2RO+icVbeHLjW8RxbKyfqUJsf17GW/Pfh3w3WhpttRxGnc8NRL7iAb8sqLKlNDd8sBcX7rt1Z0+ErHLGim8YtGjXgP7ZaKgmABUKUS3ITPupMy4DMkutcMEdplW7xPRcgnaZeZ4QFJqlL87Wi33Hn/7Jk3gxR8wfk5L3Eg5798vZJEXNPjZg2OLRJdstESrBJHIQ5bKhyaOhSsOy9+BSsRwmHsl5LyQtptGwZ9oji1pLS9VYv38FQy5NUNX5LnKPA1494jqdIIujb5EDM2U="
    # zenSonatypePassword
    - secure: "Wv/fLrCeSsjOXWrtRYmWNjeWcDEwL8ahHxHyazkHWmdDHpuLUi4R3xAxkcme1rh0+znIp3Chr1K3m3O/SbkoL/TF9Gpzf0iZDjt8ABQrsXpYmH8fOzFTJXeCx4CWQoWHNQntfUxNZQQvc9hffVkxlKN1Qi9BQ7PLEALMHEVhdvCZKgP4eeQxh8xBIwgKNd+eYW6Wq3KzmmD4DYxlJv8nYeOM9glyoxcNOPsOjf8EbV0nZZXYyYLfylO/PulJea4J6sKbwO+z8rnVow1g705R/Pweh/NAtDCveKuTvnJRN60ESnNqIkHytioFzQoJb8p5+CiVa78gA6InxjOW0K+VGlZ2XtSsxg6iyn/KH59I5L24+bg9t9fX9gZaUi15Q8enNB0IABU0+QHcHQv4FAjqC9iu5E7p7+1sMRC1q63/5Lqqds+cN6/GOXV8JiXzIXVWIHNtoPwXoE5L2T03UV/2+WrVKbynN7/BNfkfljd+tDVtt4Wt8l6kiRObyISopQT5LGwGydCMwcw043ZFyxEsNWSIzzVIr0qbqNr7Y2Br0/5aGE8cU3AHARgI7ZahXHksps7HpvtPPUHUckiTUeFyzaRl21o7FurxP/WDLjcB1BurZfIrEEZ3qbc8aPadSbYiCZD48t8cblozQfWKJePPyxjOUvL4b516riwKq9Y97Pc="
script:
- "./scripts/travis.sh"